apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: Stage1
      jobs:
        - a
        - c
        - b
        - d
jobs:
  a:
    needs: []
    environment: a
    outputs: {}
    services:
      a:
        image: a
    steps:
      - uses: s
        name: s
  b:
    needs:
      - a
    environment: ""
    outputs: {}
    steps:
      - uses: a
        name: a
  c:
    needs:
      - a
      - b
    timeout-minutes: 420
    with:
      instructions: inst
      disallowLaunchByUser: false
      approvers: 4b7f53fc-d4fe-11ec-bb55-42010a83ae55
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  d:
    needs:
      - c
    environment: ""
    outputs: {}
    steps:
      - uses: a
        name: a
