apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow monday
metadata:
  stages/v1alpha1:
  - name: Stage1
    
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
jobs:

