apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
        default: blabla
metadata:
  stages/v1alpha1:
    - name: Stage4
      jobs:
        - job3
    - name: Stage
      jobs:
        - job
    - name: Stage1
      jobs:
        - job1
    - name: Stage2
      jobs:
        - job2
jobs:
  job3:
    needs: []
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  job:
    needs:
      - job3
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  job1:
    needs:
      - job
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  job2:
    needs:
      - job1
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
