apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow 987
metadata:
  stages/v1alpha1:
    - name: Stage
      jobs:
        - job
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs: []
  job:
    name: job
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
    needs: []
env:
  a: a
  b: ",,,,,,"
