apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: Stage1
      jobs:
        - build
        - test
        - deploy
jobs:
  build:
    name: build
    needs: []
    environment: ""
    outputs: {}
    services: {}
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
  test:
    name: test
    environment: ""
    outputs: {}
    services: {}
    steps:
      - uses: sadf
        name: asf
  deploy:
    name: deploy
    needs:
      - test
    environment: ""
    outputs: {}
    services: {}
    steps:
      - uses: asdf
        name: asdf
