apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Build
      jobs:
        - call_rw_build
    - name: Stage1
      jobs:
        - exit
        - deploy
        - entry
jobs:
  call_rw_build:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw1.yaml
  job:
    needs: a
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  deploy:
    needs:
      - entry
    steps:
      - run: echo "Deploying to Prepod"
        uses: docker://golang:1.20.3-alpine3.17
        name: deploy
        shell: sh
  entry:
    needs:
      - call_rw_build
    timeout-minutes: 4320
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: 4b7f53fc-d4fe-11ec-bb55-42010a83ae55
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  exit:
    needs:
      - deploy
    timeout-minutes: 4320
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: 4b7f53fc-d4fe-11ec-bb55-42010a83ae55
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
