apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: Stage
      jobs:
        - a
        - b
jobs:
  a:
    needs: []
    environment: ""
    outputs: {}
    steps:
      - uses: a
        name: a
  b:
    needs:
      - a
    environment: ""
    outputs: {}
    steps:
      - uses: b
        name: b
