apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Test
      jobs:
        - testname
jobs:
  testname:
    steps:
      - run: echo Hello world
        uses: docker://golang:1.20.3-alpine3.17
        name: testjob
        shell: sh
