apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    
metadata:
  stages/v1alpha1:
    - name: Stage
      jobs:
        - call_rw1
jobs:
  call_rw1:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw1.yaml
