apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    

jobs:
  call_rw1:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw1.yaml