apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage
      jobs:
        - call_rw1
    - name: Stage1
      jobs:
        - job
jobs:
  call_rw1:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw1.yaml
    needs: []
  job:
    needs:
      - call_rw1
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
