apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: Stage4
      jobs: []
    - name: Stage7
      jobs: []
    - name: Stage6
      jobs: []
    - name: Stage5
      jobs: []
    - name: Stage
      jobs:
        - build
    - name: Stage3
      jobs: []
    - name: Stage1
      jobs:
        - job
    - name: Stage2
      jobs: []
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  job:
    name: job
    needs: build
