apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: wf1

on:
  workflow_dispatch:

# Single stage and single job
metadata:
  stages/v1alpha1:
    - name: stage-1
      jobs: [job-1]

jobs:
  job-1:
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
