apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: wf2

on:
  workflow_dispatch:

metadata:
  stages/v1alpha1:
    - name: stage-1
      jobs: [job-1,job-2]
    - name: stage-2
      jobs: [job-3,job-4]

jobs:
  job-1:
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
  job-2:
    needs: job-1
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
  job-3:
    needs: job-2
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
  job-4:
    needs: job-3
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
