apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: wf7

on:
  workflow_dispatch:

metadata:
  stages/v1alpha1:

jobs:
  job-1:
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
  job-2:
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
  job-3:
    needs: [job-1,job-2]
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
  job-4:
    needs: [job-1,job-2]
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
